name: Test Suite
on: [push, pull_request]


jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    defaults:
      run:
        # Adding -l {0} helps ensure conda can be found properly.
        shell: bash -l {0}
    env:
      PYTHON: 3.8
      ENV_NAME: linting
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          python-version: ${{ env.PYTHON }}
          environment-file: ci/${{ env.ENV_NAME }}.yaml
          activate-environment: ${{ env.ENV_NAME }}

      - name: Linting
        run: |
          pre-commit install
          pre-commit run -a

  tox:
    name: Tox Test Suite
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Conda Info
        run: |
          conda info
          python --version

      - name: Set up Tox
        run: pip install tox tox-conda tox-gh-actions

      - name: Run Tests
        run: tox
