name: Test Suite
on: [push, pull_request]

jobs:
  tox:
    name: Tox Test Suite
    env:
      OS: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: 3.6
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.6.0
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Setup paths
        shell: bash
        run: |
          if [[ "${{ runner.os }}" = "Windows" ]]; then
            echo "::add-path::$HOME/miniconda3"
            echo "::add-path::$HOME/miniconda3/Scripts"
          else
            echo "::add-path::$HOME/miniconda3/bin"
            echo "::add-path::$HOME/miniconda3/envs/test/bin"
          fi

      - name: Run Tox Suite
        shell: bash
        run: |
          if [[ "${{ runner.os }}" = "Windows" ]]; then
            echo $HOME
            echo $PATH
          fi
          pip install tox tox-conda
          ls
          pwd -P
          tox
