name: Test Suite
on: [push, pull_request]

jobs:
  tox:
    name: Tox Test Suite
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.6.0
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Conda Info
        run: |
          conda info
          python --version

      - name: Set up Tox
        run: pip install tox tox-conda tox-gh-actions

      - name: Run Tests
        run: tox
