name: Test Suite
on: [push, pull_request]

jobs:
  tox:
    name: Tox Test Suite
    env:
      PYTHON: 3.6
      OS: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Install Miniconda
        shell: bash
        run: |
          if [[ "${{ runner.os }}" = "Linux" ]]; then
            MINICONDA_FILENAME=Miniconda3-latest-Linux-x86_64.sh
            curl -L -o $MINICONDA_FILENAME "https://repo.continuum.io/miniconda/$MINICONDA_FILENAME"
            bash ${MINICONDA_FILENAME} -b -f -p $HOME/miniconda3
          elif [[ "${{ runner.os }}" = "macOS" ]]; then
            MINICONDA_FILENAME=Miniconda3-latest-MacOSX-x86_64.sh
            curl -L -o $HOME/miniconda.sh "https://repo.continuum.io/miniconda/$MINICONDA_FILENAME"
            bash $HOME/miniconda.sh -b -p $HOME/miniconda3
          elif [[ "${{ runner.os }}" = "Windows" ]]; then
            MINICONDA_FILENAME=Miniconda3-latest-Windows-x86_64.exe
            curl -L -o $MINICONDA_FILENAME "https://repo.continuum.io/miniconda/$MINICONDA_FILENAME"
            ./Miniconda3-latest-Windows-x86_64.exe //InstallationType=JustMe //RegisterPython=0 //S
          fi
      - name: Setup paths
        shell: bash
        run: |
          if [[ "${{ runner.os }}" = "Windows" ]]; then
            echo "::add-path::$HOME/miniconda3"
            echo "::add-path::$HOME/miniconda3/Scripts"
          else
            echo "::add-path::$HOME/miniconda3/bin"
            echo "::add-path::$HOME/miniconda3/envs/test/bin"
          fi
          echo $HOME
          echo $PATH
      - name: Run Tox Suite
        shell: bash
        run: |
          pip install tox tox-conda
          ls
          pwd -P
          tox
